services:
  frontend:
    image: localhost/um_mcc_ui_image
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_UM_MCC_API="http://ummcc.deability.co/um_mcc"

  backend:
    image: localhost/um_mcc_api_image
    ports:
      - "8000:8000"

network_mode: host
